version: '3.8'

services:
  web:
    image: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}.${CI_PIPELINE_ID}
    build: .
    container_name: ${CI_PROJECT_NAME}
    restart: unless-stopped
    environment:
      DB_NAME: ${CI_DB_NAME}
      DB_USER: ${CI_DB_USER}
      DB_PASSW: ${CI_DB_PASSW}
      DB_HOST: ${CI_DB_HOST}
networks:
  default:
    name: ${CI_PROJECT_NAME}
    driver: bridge
