version: '3.8'

services:
  noc_web:
    image: noc_web:latest
    build: .
    container_name: noc_web
    restart: unless-stopped
    ports:
      - ["80:80"]
    environment:
      DB_NAME: ""
      DB_USER: ""
      DB_PASSW: ""
      DB_HOST: ""